### ISSUE TITLE
Doesn't build with Xcode6b7

### ISSUE THREAD

**Issue by niklassaers** [bradley/iOSSwiftOpenGLCamera#1]

**Comment by bradley** [comment]
@niklassaers I haven't had time to look at this recently but I'm sure it's a minor bug having to do with swift updates. If you find it I'd be happy to accept a pull request. Alternatively, I'll try to dig into this soon.

**Comment by bradley** [comment]
This repository stopped working properly after changes were made early on to the Swift language. After efforts on my part to repair the breakages, I have decided to use Metal instead for my purposes. You can [see example code here](https://github.com/bradley/iOSSwiftMetalCamera).
