### ISSUE TITLE
Shader compiling error with Xcode 6

### ISSUE THREAD

**Issue by speaktoalvin** [bradley/iOSSwiftOpenGLCamera#2]
I almost solved all the bugs which i got in the Xcode. When i run this code now its showing that "Failed to compile shader!" which comes in this method.

```
 func compileShader(shaderName : NSString , shaderType : GLenum) -> GLuint.
```

**Comment by bradley** [comment]
This repository stopped working properly after changes were made early on to the Swift language. After efforts on my part to repair the breakages, I have decided to use Metal instead for my purposes. You can [see example code here](https://github.com/bradley/iOSSwiftMetalCamera).
