### ISSUE TITLE
It doesnt seem to compile anymore

### ISSUE THREAD

**Issue by xr1337** [bradley/iOSSwiftOpenGLCamera#6]
There seems to be a lot of swift changes which causes compiler error.

**Comment by bradley** [comment]
Yes, from the README:

> Notice: This repository stopped working properly after changes were made early on to the Swift language. After efforts on my part to repair the breakages, I have decided to use Metal instead for my purposes. You can [see example code here](https://github.com/bradley/iOSSwiftMetalCamera).
